name: authenticated_http_client
description: An advanced authenticated HTTP client introduces `factory` feature that generates request futures from API definitions in WYSIWYG style, with extra support for `mock`, `silent`.
homepage: https://github.com/leo1394/authenticated_http_client
repository: https://github.com/leo1394/authenticated_http_client
issue_tracker: https://github.com/leo1394/authenticated_http_client/issues
version: 0.2.10
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.4.0
  http_interceptor: ^2.0.0
  universal_io: ^2.2.2
  extension_dart: ^1.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - auth-http-client
  - http-interceptor
  - http-client
  - wysiwyg
  - mock-response